
# Generated by Django 5.2.13 on 2026-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickuser',
            name='pin',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clickuser',
            unique_together={('name', 'pin')},
        ),
    ]
